---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Makecondition

```{r makecondition}
library(reticulate)
use_condaenv("r-reticulate")

library(econR) # 經濟模型程式設計專題用
```


# Utility generator

```{python}
class CES: 
    def __init__(self, params):
        assert (
          type(params) is tuple # Check params's type
          and len(params) == 3 # Check params's length
          and all([ type(paramsi) is int or type(paramsi) is float for paramsi in params])
        ), "params must be a tuple of three numbers."
        self.params = params
    
    def U(self,x):
        assert (
          type(x) is tuple #Check x's type
          and len(x) == 2 # Check x's length
          and all([ type(xi) is int or type(xi) is float for xi in x])
        ), "x must be a tuple of two numbers."
        alpha1, alpha2, rho = self.params
        x1,x2=x
        u = (alpha1*(x1**rho)+alpha2*(x2**rho))**(1/rho)
        return u


```
```{python}
alpha1, alpha2, rho = (2, 3, 5)
params = (alpha1, alpha2, rho)
ces = CES(params)
x = (1, 10)
ces.U(x) # show the utility levels of x given alpha1, alpha2, rho preference parameter values
```

```{python}
import math
def q(x1):
    return math.log(x1)

```

```{python}
b = 2
ql = QL(q, b)
x = (2, 5)
ql.U(x) # returns the utility levels of x given q(x1) and b
```

```{python}
import types
class QL: 
    def __init__(self,functionq,paramb):
        assert (
          type(functionq) is types.FunctionType # Check q's type
          and ((type(b) is int) or (type(b) is float))  # Check b's  type
          ), "params must be a function and a numbers."
        self.q = functionq
        self.b = paramb
    def U(self,x):#Utility Function 
        assert (
          type(x) is tuple #Check x's type
          and len(x) == 2 # Check x's length
          and all([ type(xi) is int or type(xi) is float for xi in x])
        ), "x must be a tuple of two numbers."
        xi1,xi2=x
        return self.q(xi1)+self.b*xi2


```


## zip

```{python}
from numpy.random import default_rng
rng1 = default_rng(293)
rng2 = default_rng(283)
rng_zip = zip(rng1.uniform(50,100, size=3), rng2.uniform(2,10, size=3))


```

```{python}
iter_zip = iter(rng_zip)
next(iter_zip)
next(iter_zip)
next(iter_zip)
list(rng_zip)
```

```{r}
rng_zip = c(1,3,5)
for(x in rng_zip)
```

```{python}
for x in list(rng_zip)
```

```{r}
# R
xfun::download_file("https://www.dropbox.com/s/49y23ib21ncylyh/consumer.R?dl=1")
# Py
xfun::download_file("https://www.dropbox.com/s/u05jezbxt99z8ho/consumer.py?dl=1")
```

## Import

```{r}
source("consumer.R")
```

```{r}
consumer11 <- Consumer(c(1,1)) # preference: x*y
consumer35 <- Consumer(c(3,5)) # preference: x**3 * y**5
```

/Users/martinl/Github/econR/Rmd/consumer.py

```{python}
sys.path.extend(['/Users/martinl/Github/econR/Rmd'
])
sys.path
```

```{python}
import consumer
```

```{python}
import consumer
import consumer as cs # create an acronym for easy module access

consumer0 = cs.Consumer((3,7))
consumer1 = consumer.Consumer((5,5))
```

```{python}
import importlib as lib
lib.reload(consumer)
```

```{r}
devtools::unload(dplyr)
```

## Optimization

```{r}
fr <- function(x1, x2) {   ## Rosenbrock Banana function
    100 * (x2 - x1 * x1)^2 + (1 - x1)^2
}
```

```{r}
fr(-1.2, 1)
```

```{r}
optim()
```

```{r}
fr <- function(x) {   ## Rosenbrock Banana function
    x1 <- x[1]
    x2 <- x[2]
    100 * (x2 - x1 * x1)^2 + (1 - x1)^2
}
optim(c(-1.2, 1), fr)
```


```{python}
from scipy import optimize
import numpy as np

help(optimize.minimize)
```
```{python}
def fr(x):   ## Rosenbrock Banana function
    
    
    return 100 * (x2 - x1 * x1) ** 2 + (1 - x1)**2

```

```{r}
mat_1d = c(1.1, 1.2)
```

```{python}
mat_1d = np.array([1.1, 1.2])

print(mat_1d)
```

```{python}
mat_1d = [1.1, 1.2]
```

```{r}
mat_2d = cbind(
  c(1.1, 1.2),
  c(2.1, 2.2),
  c(3.1, 3.2)
)

print(mat_2d)
```

```{r}
mat_2d=
  c(1.1, 1.2, 2.1, 2.2, 3.1, 3.2)
mat_2d = matrix(
  mat_2d, 2,3
)
mat_2d
```

```{python}
mat_1d
mat_1d.ndim # 1 維
```

```{python}
arrayX = np.array([1,3,2.5,7])
arrayX.ndim
```

```{python}
mat_2d = np.array(
  [
    [1.1, 1.2, 3.11],
    [2.1, 2.2, 3.22],
    [3.1, 3.2, 3.33]
  ]
)

print(mat_2d)
```


```{python}
mat_2d
mat_2d.ndim
```
```{python}
mat_2d.shape
```

```{python}
mat_1d.shape
```

```{python}
mat_1d.shape = (2,1)
mat_1d.reshape(2,1)
```

```{python}
mat_1d.shape
mat_1d.ndim
```


```{python}
mat_1d
```
```{python}
vector = np.array(
  [[1.1],
  [1.2]]
)

vector
print(vector)
```

```{python}
vectorX = np.array([1.1, 1.2])
print(vectorX)
```

```{python}
X = np.array([-1.2, 1])
x1 = X[0]
x2 = X[1]
100*(x2-x1*x1)**2 + (1-x1)**2
```

```{python}
def fr(X):
    x1 = X[0]
    x2 = X[1]
    return 100*(x2-x1*x1)**2 + (1-x1)**2

```
```{python}
optimize.minimize(
  fun = fr,
  x0 = X
)
```

```{python}
def U(x,y):
  return -(x**0.2 * y**0.8) # take negative for minimization purpose

```

```{python}
cx = np.array([1, 1])
x = cx[0]
y = cx[1]
U(x, y)
```

```{python}
def newU(cx):
    x = cx[0]
    y = cx[1]
    return U(x, y)
```

```{python}
cx = np.array([1, 1])
newU(cx)
```
```{python}
def np_rize(U):
    def newU(cx):
      return U(*cx)
    return newU

```


```{python}
np_U = np_rize(U)

```

```{python}
def const_nonNeg(x,y):
    return 500-2*x-3*y

np_constraint = np_rize(const_nonNeg)
```

min np_U
st. np_constraint

```{python}
x0 = np.array([1,1])

const_dict = ({ "type": "ineq", # change to "eq" for equality constraint
  "fun": np_constraint
})

optimize.minimize(
  fun = np_U , x0=x0,
  constraints= const_dict
)
```


```{python}
c0 = np.array([1,3])
x, y = c0
```

```{python}
def cobbDouglas(x, y):
    return x**0.2 * y**0.8


def ql(x, y):
    import math
    return math.log(x)+3*y

```

```{python}
np_cobbDouglas =  npU(cobbDouglas)
np_ql = npU(ql)

```

```{python}
np_cobbDouglas(np.array([1, 2]))
```

```{python}
np_ql(np.array([1,2]))
```

### Complete script 

```{python}
def U(x,y):
  return -(x**0.2 * y**0.8) # take negative for minimization purpose

def const_nonNeg(x,y):
    return 500-2*x-3*y

def convert2arrayInputFunction(f0):
   def newFun(x_array):
       return f0(*x_array)
   return newFun
 
newU = convert2arrayInputFunction(U)
newConst_nonNeg = convert2arrayInputFunction(const_nonNeg)

## Define optimization question
const_dict = ({ "type": "ineq", # change to "eq" for equality constraint
  "fun": newConst_nonNeg
})

x0 = np.array([1,1])

optimize.minimize(
  fun = newU, x0=x0,
  constraints= const_dict
)
```
   
```{python}
params_A = (0.2, 500) # (alpha, I)
consumer_A = Consumer(params)

params_B = (0.8, 200)
consumer_B = Consumer(params)

consumer_A.prices # (2, 3)
consumer_B.prices # both show market prices

c0 = (2,3)
consumer_A.U(c0) 
consumer_B.U(c0) # show utilities of c0 for both consuemrs

consumer_A.optimise()
consumer_B.optimise() # show the optimisation result, and afterward

consumer_A.c_optim
consumer_B.c_optim # show the optimised c bundle

Consumer.prices = (5, 8)
consumer_A.optimise()
consumer_B.optimise() # show the optimisation result, and afterward

consumer_A.c_optim
consumer_B.c_optim # show the optimised c bundle

```

